spring:
  application:
    name: MSF_UI
  aop:
    auto: true
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb
server:
  port: 8085
  
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  